### ISSUE TITLE
😯😯😯😯😯😯😯😯😯Po co ten komentarz?😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯

### ISSUE THREAD

**Issue by Mvtthew** [marcelinax/Keep_your_note_safe_app#1]
😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯😯

Po co ten komentarz? tam jest co? 😯😯😯😯😯😯😯

https://github.com/marcelinax/Keep_your_not_safe_app/blob/16e80b85451fa3a5c5c61031e4b368ee6ab0d310/scripts/script.js#L2-L44

Bo ja nie wiem 😯😯😯😯😯😯😯

**Comment by marcelinax** [comment]
a siedź cicho
